name: TNTRun
main: TNTRun\Main
version: 1.1.0
api: [3.5.6, 3.5.7, 3.6.0, 3.7.0]
author: BeckenPlayZMCPE
commands:
    tr:
        usage: /tr addarena
        description: §9§lTNTRun
        permission: TNTRun.command
